source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

abstract_target 'BasePods' do
  # pods
	pod 'QLNFlowersation', :path => '../'
	# targets
  target 'TestProject'
end
